name: Actualizar clima postas rurales

on:
  schedule:
    - cron: '*/5 * * * *'   # cada 5 minutos
  workflow_dispatch:          # te permite correrlo manual también, para probar

jobs:
  actualizar-clima:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - name: Configurar credenciales GCP
        run: echo '${{ secrets.GCP_SA_KEY }}' > /tmp/sa.json

      - name: Ejecutar script de clima
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/sa.json
        run: python clima_postas.py
